name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit test
        run: npm run test

      - name: Run linter
        run: npm run lint 
      
      - name: Generate code coverage
        run: npm run test -- --coverage

      - name: Log into Docker Hub 
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/hexashop:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/hexashop:latest

      - name: Deploy on EC2 
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          port: ${{secrets.EC2_PORT}}
          script: |
            docker pull ${{secrets.DOCKER_USERNAME}}/hexashop:latest
            docker rm  -f hexashop || true
            docker run -d -p 80:3000 --name hexashop ${{secrets.DOCKER_USERNAME}}/hexashop:latest