- name: Set Docker image tag
  run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

- name: Build Docker image
  run: docker build --no-cache -t ${{secrets.DOCKER_USERNAME}}/hexashop:${{ env.IMAGE_TAG }} .

- name: Push Docker image to Docker Hub
  run: docker push ${{secrets.DOCKER_USERNAME}}/hexashop:${{ env.IMAGE_TAG }}

- name: Deploy on EC2 
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{secrets.EC2_HOST}}
    username: ubuntu
    key: ${{secrets.EC2_SSH_KEY}}
    port: ${{secrets.EC2_PORT}}
    script: |
      docker stop hexashop || true
      docker rm hexashop || true
      docker pull ${{secrets.DOCKER_USERNAME}}/hexashop:${{ env.IMAGE_TAG }}
      docker run -d -p 80:3000 --name hexashop ${{secrets.DOCKER_USERNAME}}/hexashop:${{ env.IMAGE_TAG }}
